# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/pydob/ <varies>
# Pattern: https://github.com/pydob/easy-as-pypi#🥧
# License: MIT
#
#   https://github.com/pydob/easy-as-pypi#🥧

version: 2

python:
  version: 3.8
  install:
     - method: pip
       path: .

