# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/pydob/ <varies>
# Pattern: https://github.com/pydob/easy-as-pypi#🥧
# License: MIT

# COPYD/2023-05-17: Everything below copied from:
#
#   https://docs.readthedocs.io/en/stable/config-file/v2.html

# ***

# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    #
    #  nodejs: "19"
    #  rust: "1.64"
    #  golang: "1.19"

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py

# If using Sphinx, optionally build your docs in additional formats such as PDF
#
#  formats:
#     - pdf

# Optionally declare the Python requirements required to build your docs
#
#  python:
#     install:
#     - requirements: docs/requirements.txt

