# vim:tw=0:ts=2:sw=2:et:norl
# Author: Landon Bouma <https://tallybark.com/>
# Project: https://github.com/pydob/easy-as-pypi#🥧
# License: MIT

# CXREF: https://github.com/readthedocs/actions/tree/v1/preview
#   https://github.com/readthedocs/actions

---

name: readthedocs/actions
on:
  pull_request_target:
    types:
      - opened
      # Execute this action only on PRs that touch
      # documentation files.
      # paths:
      - "docs/**"

permissions:
  pull-requests: write

jobs:
  pull-request-links:
    runs-on: ubuntu-latest
    steps:
      - uses: readthedocs/actions/preview@v1
        with:
          project-slug: "easy-as-pypi"
